// import {
//   clear,
//   changeSign,
//   addDecimal,
//   calculatePercent,
//   doOperation,
//   calculateValue,
//   processDigit,
// } from "./listeners.ts";

// export const buttonsData = [
//   {
//     name: "Clear Button",
//     displayText: "C",
//     classes: ["bg-dark-grey"],
//     listener: clear,
//   },
//   {
//     name: "Sign Button",
//     displayText: "+/-",
//     classes: ["bg-dark-grey"],
//     listener: changeSign,
//   },
//   {
//     name: "Percent Button",
//     displayText: "%",
//     classes: ["bg-dark-grey"],
//     listener: calculatePercent,
//   },
//   {
//     name: "Divide Button",
//     displayText: "/",
//     classes: ["bg-orange"],
//     listener: doOperation,
//   },
//   {
//     name: "Seven Button",
//     displayText: "7",
//     classes: ["bg-light-grey"],
//     listener: processDigit,
//   },
//   {
//     name: "Eight Button",
//     displayText: "8",
//     classes: ["bg-light-grey"],
//     listener: processDigit,
//   },
//   {
//     name: "Nine Button",
//     displayText: "9",
//     classes: ["bg-light-grey"],
//     listener: processDigit,
//   },
//   {
//     name: "Multiply Button",
//     displayText: "x",
//     classes: ["bg-orange"],
//     listener: doOperation,
//   },
//   {
//     name: "Four Button",
//     displayText: "4",
//     classes: ["bg-light-grey"],
//     listener: processDigit,
//   },
//   {
//     name: "Five Button",
//     displayText: "5",
//     classes: ["bg-light-grey"],
//     listener: processDigit,
//   },
//   {
//     name: "Six Button",
//     displayText: "6",
//     classes: ["bg-light-grey"],
//     listener: processDigit,
//   },
//   {
//     name: "Minus Button",
//     displayText: "-",
//     classes: ["bg-orange"],
//     listener: doOperation,
//   },
//   {
//     name: "One Button",
//     displayText: "1",
//     classes: ["bg-light-grey"],
//     listener: processDigit,
//   },
//   {
//     name: "Two Button",
//     displayText: "2",
//     classes: ["bg-light-grey"],
//     listener: processDigit,
//   },
//   {
//     name: "Three Button",
//     displayText: "3",
//     classes: ["bg-light-grey"],
//     listener: processDigit,
//   },
//   {
//     name: "Plus Button",
//     displayText: "+",
//     classes: ["bg-orange"],
//     listener: doOperation,
//   },
//   {
//     name: "Zero Button",
//     displayText: "0",
//     classes: ["bg-light-grey"],
//     listener: processDigit,
//   },
//   {
//     name: "Decimal Button",
//     displayText: ".",
//     classes: ["bg-light-grey"],
//     listener: addDecimal,
//   },
//   {
//     name: "Equals Button",
//     displayText: "=",
//     classes: ["bg-orange"],
//     listener: calculateValue,
//   },
// ];
